{
    "COMMENT": "NOTE: this file is autogenerated; built at Sun Oct 11 2020 18:21:44 GMT+0200 (GMT+02:00) with binhack-maker v1.0a",
    "binhacks": {
        "Priw8_th16ice_binhack_3E124": {
            "addr": "Rx3E124",
            "code": "81 fa 00 00 00 80 b8 ff ff ff 7f"
        },
        "Priw8_th16ice_binhack_12945": {
            "addr": "Rx12945",
            "code": "e9 [codecave:Priw8_th16ice_bulletManagerPatch]"
        },
        "Priw8_th16ice_binhack_426F1": {
            "addr": "Rx426F1",
            "code": "e9 [codecave:Priw8_th16ice_useReleasePatch]"
        },
        "Priw8_th16ice_binhack_DD7A": {
            "addr": "RxDD7A",
            "code": "e9 [codecave:Priw8_th16ice_releaseIsActivePatch] 90 90"
        }
    },
    "codecaves": {
        "Priw8_th16ice_FREEZE_DURATIONS": "3c 00 00 00 50 00 00 00 64 00 00 00 73 00 00 00 7d 00 00 00 87 00 00 00",
        "Priw8_th16ice_FREEZE_INIT_RADIUS": "00 00 61 45",
        "Priw8_th16ice_FREEZE_PROPAGATE_RADIUS": "00 00 c8 43",
        "Priw8_th16ice_FREEZE_INIT_POS": "00 00 00 00 00 00 00 00",
        "Priw8_th16ice_FREEZE_TIMER": "00 00 00 00",
        "Priw8_th16ice_bulletManagerPatch": "f7 41 20 00 00 00 80 0f 84 10 00 00 00 60 e8 18 00 00 00 61 31 c0 ba 4a 29 41 00 ff e2 ba 70 1e 41 00 ff d2 ba 4a 29 41 00 ff e2 8b 81 14 12 00 00 48 85 c0 0f 84 21 00 00 00 89 81 14 12 00 00 f7 41 20 00 00 00 40 0f 85 06 00 00 00 e8 1a 00 00 00 c3 81 61 20 ff ff ff bf c3 81 61 20 ff ff ff 7f 6a 04 b8 40 68 41 00 ff d0 c3 89 c7 8b 1d ac 6d 4a 00 8b 5b 70 8b 5b 04 85 db 0f 84 75 00 00 00 8b 33 85 f6 0f 84 eb ff ff ff 39 ce 0f 84 e3 ff ff ff f7 46 20 00 00 00 80 0f 85 d6 ff ff ff d9 81 20 0c 00 00 d8 a6 20 0c 00 00 d8 c8 d9 81 24 0c 00 00 d8 a6 24 0c 00 00 d8 c8 de c1 b8 <codecave:Priw8_th16ice_FREEZE_PROPAGATE_RADIUS> d8 18 9b df e0 9b 9e 0f 87 a6 ff ff ff 81 4e 20 00 00 00 80 81 4e 20 00 00 00 40 89 be 14 12 00 00 60 8d 9e 20 0c 00 00 e8 [codecave:Priw8_th16ice_spawnFreezeAnim] 61 e9 80 ff ff ff c3",
        "Priw8_th16ice_useReleasePatch": "60 e8 08 00 00 00 61 b8 f6 26 44 00 ff e0 e8 bd 00 00 00 8b 3d a4 6d 4a 00 89 87 d8 00 00 00 c7 47 30 01 00 00 00 48 bf <codecave:Priw8_th16ice_FREEZE_DURATIONS> 8b 3c 87 be <codecave:Priw8_th16ice_FREEZE_TIMER> 89 3e b9 3c 58 4a 00 8b 0c 81 29 0d 08 58 4a 00 ba 00 c6 42 00 ff d2 8b 15 f8 6e 4a 00 8b 8a 10 06 00 00 b8 <codecave:Priw8_th16ice_FREEZE_INIT_POS> 89 08 8b 8a 14 06 00 00 89 48 04 b8 00 f6 46 00 ff d0 89 c6 8b 0d b8 6d 4a 00 8b 49 0c 68 e7 00 00 00 56 b8 20 7b 40 00 ff d0 8b 1d f8 6e 4a 00 8d 9b 10 06 00 00 8b 03 89 46 2c 8b 43 04 89 46 30 89 be a4 04 00 00 31 c0 89 86 e0 04 00 00 89 86 e4 04 00 00 89 86 e0 05 00 00 89 86 e4 05 00 00 56 8d 04 24 83 ec 04 50 b8 d0 e7 46 00 ff d0 83 c4 04 c3 a1 08 58 4a 00 3b 05 50 58 4a 00 0f 8e 06 00 00 00 b8 06 00 00 00 c3 3b 05 4c 58 4a 00 0f 8e 06 00 00 00 b8 05 00 00 00 c3 3b 05 48 58 4a 00 0f 8e 06 00 00 00 b8 04 00 00 00 c3 3b 05 44 58 4a 00 0f 8e 06 00 00 00 b8 03 00 00 00 c3 3b 05 40 58 4a 00 0f 8e 06 00 00 00 b8 02 00 00 00 c3 b8 01 00 00 00 c3",
        "Priw8_th16ice_spawnFreezeAnim": "b8 00 f6 46 00 ff d0 89 c6 8b 0d b8 6d 4a 00 8b 49 0c 68 c6 00 00 00 56 b8 20 7b 40 00 ff d0 8b 03 89 46 2c 8b 43 04 89 46 30 89 be a4 04 00 00 31 c0 89 86 e0 04 00 00 89 86 e4 04 00 00 89 86 e0 05 00 00 89 86 e4 05 00 00 56 8d 04 24 83 ec 04 50 b8 d0 e7 46 00 ff d0 83 c4 04 6a 00 6a 3b b8 50 e1 45 00 ff d0 c3",
        "Priw8_th16ice_releaseIsActivePatch": "b8 <codecave:Priw8_th16ice_FREEZE_TIMER> 83 38 00 0f 84 2d 00 00 00 60 e8 35 00 00 00 61 ff 08 83 38 00 0f 84 07 00 00 00 b8 7f dd 40 00 ff e0 60 6a 00 6a 3c b8 50 e1 45 00 ff d0 61 b8 7f dd 40 00 ff e0 c7 46 30 00 00 00 00 b8 7f dd 40 00 ff e0 bf <codecave:Priw8_th16ice_FREEZE_TIMER> 8b 3f 8b 1d ac 6d 4a 00 8b 5b 70 85 db 0f 84 6f 00 00 00 8b 5b 04 85 db 0f 84 64 00 00 00 8b 0b 85 c9 0f 84 eb ff ff ff f7 41 20 00 00 00 80 0f 85 de ff ff ff b8 <codecave:Priw8_th16ice_FREEZE_INIT_POS> d9 00 d8 a1 20 0c 00 00 d8 c8 d9 40 04 d8 a1 24 0c 00 00 d8 c8 de c1 b8 <codecave:Priw8_th16ice_FREEZE_INIT_RADIUS> d8 18 9b df e0 9b 9e 0f 87 b0 ff ff ff 81 49 20 00 00 00 80 89 b9 14 12 00 00 60 8d 99 20 0c 00 00 e8 [codecave:Priw8_th16ice_spawnFreezeAnim] 61 e9 91 ff ff ff c3",
        "protection": "0x40"
    }
}